### ISSUE TITLE
Wrong post dates

### ISSUE THREAD

**Issue by WilliamDavidHarrison** [oyepriyansh/DevTweet#1]
![image](https://github.com/oyepriyansh/DevTweet/assets/87287585/b08b1f19-d0bc-4664-a5fd-438c79154877)

**Comment by WilliamDavidHarrison** [comment]
Nevermind, I just realised the dates are manually specified.

**Comment by oyepriyansh** [comment]
I just added that for testing purposes. I will edit the post.
