### ISSUE TITLE
feat: Adding a Footer to Corresponding Pages 

### ISSUE THREAD

**Issue by SAGARSINGH-1** [oyepriyansh/DevTweet#102]
### Description

I'm proposing the addition of a footer component to all corresponding pages in the project. A footer can provide essential information, links, and a consistent user experience across the site. This feature will enhance navigation and usability.

### Screenshots

Implement a Footer here : 

![image](https://github.com/oyepriyansh/DevTweet/assets/81561733/933cbe4e-e028-4e79-b032-4cb49777b4af)

### Ready to Work?

- [X] I want to work on this issue

**Comment by SAGARSINGH-1** [comment]
hey @oyepriyansh is there any Design where I get the reference from?

**Comment by SAGARSINGH-1** [comment]
hey @oyepriyansh if you need changes let me know and please add Hacktoberfest labels.

**Comment by oyepriyansh** [comment]
> hey @oyepriyansh if you need changes let me know and please add Hacktoberfest labels.

Yep it would be improved.

**Comment by SAGARSINGH-1** [comment]
Improvement: I directly added a Footer tag and its code in all files we can just make a component and implement that component where we need a Footer.
