### ISSUE TITLE
feat: Adding Active state in any pages to navbar list..

### ISSUE THREAD

**Issue by SAGARSINGH-1** [oyepriyansh/DevTweet#103]
### Description

We need to enhance the user experience on our website by adding an active state to the navigation bar for all pages. Currently, when users navigate through our site, it's not always clear which page they are currently on. By implementing an active state in the navigation bar, we can visually highlight the current page, making it easier for users to understand their navigation context.

### Screenshots

![image](https://github.com/oyepriyansh/DevTweet/assets/81561733/68f1babf-fe11-4d61-8c54-5bd335fd664e)

### Ready to Work?

- [ ] I want to work on this issue

**Comment by oyepriyansh** [comment]
assigned to you.

**Comment by SAGARSINGH-1** [comment]
Bro, I tried to implement the isActive() function but can't get the expected output. It was maybe I'll didn't have enough knowledge in .astros.

**Comment by Pawank06** [comment]
Hey, I want to work on this issue ? Also we need to add an hover effect to navbar elements!!

**Comment by oyepriyansh** [comment]
> Hey, I want to work on this issue ? Also we need to add an hover effect to navbar elements!!

assigned to you @Pawank06

**Comment by oyepriyansh** [comment]
@Pawank06 any updates?

**Comment by oyepriyansh** [comment]
@Shoyebaktar-shirol any update?

**Comment by Ganesh107** [comment]
if its still open i would like to work on this

**Comment by wdhdev** [comment]
@Ganesh107 I've assigned you.

**Comment by Ganesh107** [comment]
sorry no idea on astro, I should have checked before asking sorry!!

**Comment by shaurya5** [comment]
#201 I think this fixes the issue

**Comment by wdhdev** [comment]
@shaurya5 Merged, however it only adds highlighting when hovering over, not an actual colour change when you are on that page.

**Comment by shaurya5** [comment]
This is working fine in development but failing in production. I'll check on that.

**Comment by shaurya5** [comment]
Hi, can you review #202?

**Comment by oyepriyansh** [comment]
fixed in #201
