### ISSUE TITLE
feat: Enhance UI by adding a subtle border to the post component for improved visual appeal and user experience.

### ISSUE THREAD

**Issue by SAGARSINGH-1** [oyepriyansh/DevTweet#112]
### Description

Adding some border to all the posts to improve visual appeal for user.

### Screenshots

Before: 
<img width="938" alt="image" src="https://github.com/oyepriyansh/DevTweet/assets/81561733/384c0228-c118-4723-9ea9-a516f5f333bc">

After:

<img width="938" alt="image" src="https://github.com/oyepriyansh/DevTweet/assets/81561733/53687135-f9dc-485b-94e5-8a13609a1203">

### Ready to Work?

- [x] I want to work on this issue

**Comment by oyepriyansh** [comment]
Assigned to you.
