### ISSUE TITLE
Bug: author section is not responsive on mobile

### ISSUE THREAD

**Issue by oyepriyansh** [oyepriyansh/DevTweet#114]
### Description

align one profile in a row in mobile view

### Screenshots

![image](https://github.com/oyepriyansh/DevTweet/assets/83062406/8542cd65-720e-4d98-a860-5f730fbf6800)

### What browsers are you seeing the problem on?

Other

### Ready to Work?

- [ ] I want to work on this issue

**Comment by oyepriyansh** [comment]
if anyone wants to work on this issue, please let me know

**Comment by ChiragAgg5k** [comment]
I can work on this issue. can you assign it to me?

**Comment by oyepriyansh** [comment]
> I can work on this issue. can you assign it to me?

assigned to you @ChiragAgg5k.

**Comment by Chitresh-code** [comment]
@oyepriyansh if its available, I would like to work on the issue.

**Comment by oyepriyansh** [comment]
> @oyepriyansh if its available, I would like to work on the issue.
> 
> 

Already fixed
