### ISSUE TITLE
Bug: Icon and text color are deifferent on hovering

### ISSUE THREAD

**Issue by techmannih** [oyepriyansh/DevTweet#121]
### Description

Hello @oyepriyansh ,
I found an issue in  your website in which  hovering on icon both icon and text color same but on hovering on text both icon and text color are different .Really I check again now and I found , You can also check this issue 
and I want to work on this issue ...please assign me 

### Screenshots

![2023-10-06_07-46](https://github.com/oyepriyansh/DevTweet/assets/125847751/e58e7c43-347c-4c2e-a1ad-e9437776e2ba)

### What browsers are you seeing the problem on?

Firefox

### Ready to Work?

- [X] I want to work on this issue

**Comment by techmannih** [comment]
Hello @oyepriyansh  ,
I want to work on this issue please assign me

**Comment by techmannih** [comment]
Hello @oyepriyansh ,
I want to work on it please assign me

**Comment by ujjawalsh99** [comment]
Hi @oyepriyansh ,
I fixed the mentioned issue.
Please review the fix #139 
Thanks

**Comment by WilliamDavidHarrison** [comment]
I have merged your PR.

**Comment by techmannih** [comment]
Hello @WilliamDavidHarrison 
How are you merged his PR. This issue assign me by @oyepriyansh and I working on it . Why are you doing  something wrong

**Comment by techmannih** [comment]
And @ujjawalsh99 
What is this and you not know about the open source  I have assigned this issue and I will create a PR. This is not your home without assigned you . You don't work on it and not create pR

**Comment by techmannih** [comment]
@oyepriyansh and @WilliamDavidHarrison , 
What are you doing without assign him how are you merged his PR .
You also don't know abut it .

**Comment by techmannih** [comment]
this issue did create by me ..And also assign me then i create a Pr of this issue and you will also merged it

**Comment by WilliamDavidHarrison** [comment]
Who really cares? It's how open source works. Someone just got to fixing it before you, there's always other ways to contribute.
