### ISSUE TITLE
feat: Make the navbar sticky

### ISSUE THREAD

**Issue by accodes21** [oyepriyansh/DevTweet#125]
### Description

Make the navbar sticky so that the user does not need to scroll all the way up to the top, also it will be easy to navigate to different pages .

### Ready to Work?

- [X] I want to work on this issue

**Comment by amrahs02** [comment]
can i work on this issue?

**Comment by oyepriyansh** [comment]
@accodes21 can you give a look?

**Comment by oyepriyansh** [comment]
Assigned to you @accodes21
