### ISSUE TITLE
Bug: Author should be white in dark mode

### ISSUE THREAD

**Issue by amrahs02** [oyepriyansh/DevTweet#127]
### Description

In Dark mode the color of "Authors" should be white. 

### Screenshots

![Screenshot from 2023-10-07 08-34-38](https://github.com/oyepriyansh/DevTweet/assets/65103353/0e573281-3eaa-404a-8487-a71da7f7b28f)

![Screenshot from 2023-10-07 08-34-43](https://github.com/oyepriyansh/DevTweet/assets/65103353/acce5991-abcc-4d94-8976-ca762861a398)

### What browsers are you seeing the problem on?

Firefox

### Ready to Work?

- [X] I want to work on this issue

**Comment by amrahs02** [comment]
Assign me so that i can work on this .

**Comment by oyepriyansh** [comment]
Assigned to you
