### ISSUE TITLE
Bug: Overflow issue

### ISSUE THREAD

**Issue by divyanshudhruv** [oyepriyansh/DevTweet#129]
### Description

The header and text are not well formatted.

### Screenshots

<img width="548" alt="image" src="https://github.com/oyepriyansh/DevTweet/assets/71079602/5e08c04f-5dff-46aa-b85e-09808429ddd7">

### What browsers are you seeing the problem on?

Microsoft Edge

### Ready to Work?

- [ ] I want to work on this issue

**Comment by SAGARSINGH-1** [comment]
hey @oyepriyansh I want to work on this overflow issue please assign it to me.

**Comment by oyepriyansh** [comment]
> hey @oyepriyansh I want to work on this overflow issue please assign it to me.

assigned to you @SAGARSINGH-1.
