### ISSUE TITLE
feat: add custom 404 page

### ISSUE THREAD

**Issue by oyepriyansh** [oyepriyansh/DevTweet#132]
### Description

Currently the website shows a vercel 404 page

### Ready to Work?

- [ ] I want to work on this issue

**Comment by oyepriyansh** [comment]
lmk if anyone wants to work on this issue

**Comment by i-am-SnehaChauhan** [comment]
Hey @oyepriyansh, i Would like to contribute to this. Please assign this to me

**Comment by oyepriyansh** [comment]
> Hey @oyepriyansh, i Would like to contribute to this. Please assign this to me

assigned to you.

**Comment by oyepriyansh** [comment]
@i-am-SnehaChauhan have u done it?

**Comment by i-am-SnehaChauhan** [comment]
Hey @oyepriyansh, Actually, I am currently in the midst of my midterm exams. Could you please give me 3-5 days? I will complete this and submit my pull request as soon as possible.

**Comment by oyepriyansh** [comment]
sure

> Hey @oyepriyansh, Actually, I am currently in the midst of my midterm exams. Could you please give me 3-5 days? I will complete this and submit my pull request as soon as possible.

**Comment by 07-Chandra** [comment]
i want to work on this feature could you assign please ... ?

**Comment by i-am-SnehaChauhan** [comment]
Hey @07-Chandra I am already working on it and It's almost done.

**Comment by 07-Chandra** [comment]
ok good luck 👍
