### ISSUE TITLE
feat: add a filter feature to filter posts based on the options provided in the picture

### ISSUE THREAD

**Issue by Siddharth1006** [oyepriyansh/DevTweet#134]
### Description

Its hard to find what the post is about until we click onto it. Like If there was a feature that allowed me to filter out all posts that are on the topic say - "Learning Resources" or if I wanted filter out posts on the different "opinions/perspectives" people had on different topic, that would be easier and more relatable. It would also solve the issue of searching for posts that are similar that I wish to read because they will be under 1 category.

### Screenshots

![image](https://github.com/oyepriyansh/DevTweet/assets/54227620/43d29fc1-db54-420a-845c-8e894841e5f3)

### Ready to Work?

- [X] I want to work on this issue

**Comment by oyepriyansh** [comment]
assigned to you.
