### ISSUE TITLE
Hacktoberfest Excluded?

### ISSUE THREAD

**Issue by Richardhartleydev** [oyepriyansh/DevTweet#146]
### What would you like to share?

Might want to check why this is? 

![Screenshot (2785)](https://github.com/oyepriyansh/DevTweet/assets/143696125/14e7f277-70cb-474f-845d-f557153a10b0)

**Comment by oyepriyansh** [comment]
no idea why this repository is excluded from hacktoberfest

**Comment by Sanchitbajaj02** [comment]
> no idea why this repository is excluded from hacktoberfest

I think it is because so many people have made the pull request which didn't satisfy the basic commit criteria this year, that's why it is excluded

**Comment by ArnavK-09** [comment]
ad ;/
