### ISSUE TITLE
feat:Make dynamic copyright year at footer 

### ISSUE THREAD

**Issue by techmannih** [oyepriyansh/DevTweet#156]
### Description

make dynamic copyright year at footer

### Screenshots

![Screenshot_2023-10-20_01-22-43](https://github.com/oyepriyansh/DevTweet/assets/125847751/54b42383-c3fb-402d-b2fc-b853a13466a8)

### Ready to Work?

- [X] I want to work on this issue

**Comment by WilliamDavidHarrison** [comment]
Assigned to you!
