### ISSUE TITLE
Bug: Homescreen's what to post section spacing and ui issues

### ISSUE THREAD

**Issue by Sanchitbajaj02** [oyepriyansh/DevTweet#166]
### Description

The 'what to post' section on the home page has so much spacing and it is looking odd for some reason. Also, while hovering on bullet points, the cursor isn't changing to the selection cursor. Although it is not selecting or going anywhere a better user experience would be to change the cursor to pointer.

Also at the footer, it is written:  Copyright © 2023.All rights reserved.

But I think a professional way would be: Copyright © 2023 DevTweet | All rights reserved.

So, I want to work on these issues.

### What browsers are you seeing the problem on?

Brave, Chrome, Microsoft Edge

### Ready to Work?

- [X] I want to work on this issue

**Comment by oyepriyansh** [comment]
assigned to you
