### ISSUE TITLE
Bug: Hover Problem In The NavBar

### ISSUE THREAD

**Issue by divyanshudhruv** [oyepriyansh/DevTweet#25]
##  Hover problem

> The **Icons** And The **Corresponding** **Text** Are Not Well Programmed. 

> When User Clicks On **`Icon`** -> Only Icons Get **Highlighted**

> Whe User Clicks On **`Text`** -> Both Icon And The Corresponding Text Get **Highlighted**

<br>

## Some Screenshots

> **Hovering On Texts-** 

><img width="404" alt="image" src="https://github.com/oyepriyansh/DevTweet/assets/71079602/71a4b1ed-3208-4161-b3f3-f662aecf187d">

<br>

> **Hovering On Icons-**

> <img width="404" alt="image" src="https://github.com/oyepriyansh/DevTweet/assets/71079602/f12ef99d-05a6-47c8-b743-1031f3a5d5c3">

### What browsers are you seeing the problem on?

Microsoft Edge

### Ready to Work?

- [ ] I want to work on this issue

**Comment by WilliamDavidHarrison** [comment]
@oyepriyansh This seems like a simple CSS issue, I might try and fix it later today.

**Comment by WilliamDavidHarrison** [comment]
@oyepriyansh Nvm I don't think I can as I cannot really understand the layout code as it is all separated on new lines.

**Comment by oyepriyansh** [comment]
Alr

**Comment by divyanshudhruv** [comment]
### @oyepriyansh You can also change the color from blue to- `#8D8AFE` and on hover to- `#6764FB` as it will enhance the accessibility.

<br>

> **Normal:** 

<img width="32" alt="image" src="https://github.com/oyepriyansh/DevTweet/assets/71079602/600f73bc-48a9-448c-9d4c-2863d995eca9">

<br>

> **On Hovering:** 

<img width="32" alt="image" src="https://github.com/oyepriyansh/DevTweet/assets/71079602/e38c3cd1-3e93-4c14-acd1-740d32f3935e">

**Comment by techmannih** [comment]
hello @oyepriyansh ,
I want to work on this issue .....please assign me

**Comment by oyepriyansh** [comment]
> hello @oyepriyansh , I have checked just this issue in your website and its a real issue at this time also so I want to work on this issue .....please assign me
assigned
