### ISSUE TITLE
Unauthorized Use of Open Source Project

### ISSUE THREAD

**Issue by DuroCodes** [oyepriyansh/DevTweet#26]
### What would you like to share?

**Repository/Website:** [https://github.com/oyepriyansh/DevTweet]
**Original Project:** [https://github.com/shakenbird/igp-forum-site]

I have identified that the repository/website linked above has copied my open-source project without proper attribution or permission. This is a violation of the project's open-source license and intellectual property rights.

## Evidence

1. The `astro.config.mjs` is **exactly** the same. Even down to the 2 empty lines, which I did on accident, is the same in your `astro.config.mjs`.
2. You're using my API to generate images for your posts (the API isn't even working as of now)
3. All of your components are the same, including `YoutubeEmbed.tsx`, which isn't even used on the website.
4. Your entire codebase is the **exact** same.

## Request

I kindly request the following actions be taken:

1. **Immediate Removal:** The infringing repository/website must be taken down immediately.
2. **Attribution:** If you wish to continue to use my project, you must provide credit to the authors, @DuroCodes, @shakenbird, and @ImagineGamingPlay.

## Action

Failure to comply with these requests within a reasonable timeframe may result in legal action being taken against the infringing parties. Please note that intellectual property rights are protected by law, and violations can have serious consequences.

I am open to resolving this matter amicably, and I hope we can reach a mutually beneficial solution.

Thank you for your prompt attention to this matter.

Sincerely,

https://github.com/DuroCodes
durocodes@gmail.com

**Comment by WilliamDavidHarrison** [comment]
We won't take down the repository or website as the entire point of open-source is being able to use other people's code. Also, your repository doesn't even have a LICENSE, so as far as I'm concerned, we are allowed to use it.

**Comment by DuroCodes** [comment]
I understand your perspective, however, unlicensed code does not mean it's free to use.

Unlicensed code means that the author retains all rights to their source code, and others **do not** have the right to reproduce, distribute, or create derivative works from that code without explicit permission from the original author. This protection extends to the original code, irrespective of whether it's available publicly.

I kindly request that you consider providing proper attribution for the code you have used, in line with the MIT license terms that you have recently applied. (Your MIT license has the term that you have to credit the original author anyways)

**Comment by WilliamDavidHarrison** [comment]
If the code is unlicensed, it can be used by anyone as there is nothing saying you can't.

**Comment by shakenbird** [comment]
Anytime you create a code yourself, it becomes your intellectual property, putting it under exclusive copyright by default. A license for the code **could** grant others access to use the code, however by not providing a license it is common sense that the code is not available to be copied. In addition to the legal facts, let's note that it is completely immoral to steal someone's code without giving any credit. Would you want someone to steal a code and website design you made without credit? 
If that's not simple enough for you, here's an analogy-- if someone committed a murder at a park and claimed it's legal because there's no sign at the park that says you can't murder people, does that make it legal?

**Comment by WilliamDavidHarrison** [comment]
We are willing to give you credit in the README if you would like.

**Comment by oyepriyansh** [comment]
@DuroCodes, my apologies for not giving credits earlier, but I have now added them. You can find the update here: https://github.com/oyepriyansh/DevTweet/commit/7400b78d270ef03657e59bc2a2bdddd04c5b5398
