### ISSUE TITLE
feat: Wasted space on blog 

### ISSUE THREAD

**Issue by Sanchitbajaj02** [oyepriyansh/DevTweet#49]
### Description

Hi, your webapp is amazing and it looks great. But I think the space that you've left is too much. Although you tried to make it like a twitter feed, but considering the UX of twitter on a blogging seems little bit different 😅.

If you feel like that and wants you to make it look more amazing, let me know and assign this issue to me.

### Ready to Work?

- [X] I want to work on this issue

**Comment by oyepriyansh** [comment]
here you go @Sanchitbajaj02

**Comment by oyepriyansh** [comment]
> Could you please mark this issue as well as PR #55 as hacktoberfest-accepted

done
