### ISSUE TITLE
feat: contact footer 

### ISSUE THREAD

**Issue by Owais24code** [oyepriyansh/DevTweet#61]
### Description

create a footer where contact details should be. please assign  this issue under hacktoberfest 2023.

### Ready to Work?

- [x] I want to work on this issue

**Comment by oyepriyansh** [comment]
assigned to you

**Comment by Rishav9911** [comment]
hello there, can i work on this? @oyepriyansh

**Comment by oyepriyansh** [comment]
> hello there, can i work on this? @oyepriyansh 

Currently @Owais24code working on this issues, if he is not able to do it then you will be assigned.
