### ISSUE TITLE
Bug: Improvement in CSS of your project 

### ISSUE THREAD

**Issue by Soyvor** [oyepriyansh/DevTweet#71]
### Description

Comments: Add comments to your CSS to describe the purpose and usage of each section or block. Comments can help you and other developers understand the code better.

Modularization: Consider breaking down your CSS into smaller, modular files based on the components or sections of your website. This can make it easier to manage and maintain your styles.

Variables: You're already using CSS custom properties (variables) for some properties, which is great for maintainability. Consider using variables for other properties like colors, spacing, and font sizes to create a more consistent and easily customizable design.

Group Related Properties: Group related CSS properties together, such as layout properties (e.g., margin, padding) and typography properties (e.g., font-size, font-weight). This can make your CSS more readable.

Responsive Design: You've included a media query for screens with a maximum width of 700px, which is good for responsiveness. Consider adding more media queries for different screen sizes to ensure your site looks good on various devices.

Selector Specificity: Be cautious with overly specific selectors, as they can make your CSS harder to override and maintain. Try to keep selector specificity as low as possible.

### Ready to Work?

- [ ] I want to work on this issue

**Comment by techmannih** [comment]
Hello @Soyvor @oyepriyansh ,
I want to work on this issue....please assign me this issue

**Comment by oyepriyansh** [comment]
@techmannih assigned to you
