### ISSUE TITLE
feat: Improve the cards in Authors section

### ISSUE THREAD

**Issue by pooranjoyb** [oyepriyansh/DevTweet#73]
### UI changes:

- It would be better if we could make the cards in the `Author` section horizontal. 
- This would make the UI more appealing.

### Screenshots

![image](https://github.com/oyepriyansh/DevTweet/assets/90945182/ce44d7aa-411e-46dc-98a6-2c67f2d09123)

### Ready to Work?

- [X] I want to work on this issue

**Comment by oyepriyansh** [comment]
assigned to you.
