### ISSUE TITLE
Bug:  navbar != responsive

### ISSUE THREAD

**Issue by dev-abhishekkr** [oyepriyansh/DevTweet#77]
### Description

The navigation bar header is not responsive, I can make the header navigation bar responsive.

### Screenshots

![Screenshot (113)](https://github.com/oyepriyansh/DevTweet/assets/144001779/d3865a6f-34d6-49e3-9764-e599e6549f52)

### Ready to Work?

- [X] I want to work on this issue

**Comment by oyepriyansh** [comment]
assigned to you
