### ISSUE TITLE
Bug: The UI is way too narrow for wider screens. Theme Icon is also Buggy.

### ISSUE THREAD

**Issue by CodeStrate** [oyepriyansh/DevTweet#80]
### Description

The UI is pretty narrow and gives a lot of space to be wasted.

Also when we first load into the site, the theme icon shows the sun and once we switch and switch back it shows the moon in dark mode.

To reproduce
- Load the site.
- Switch themes.

### Screenshots

![image](https://github.com/oyepriyansh/DevTweet/assets/56911705/6ef1466a-f762-44f3-9806-a1c45ea88102)

![image](https://github.com/oyepriyansh/DevTweet/assets/56911705/e353e199-e7fe-4581-b520-2c24a5b7f99f)
![image](https://github.com/oyepriyansh/DevTweet/assets/56911705/7b86c854-1f10-4319-8121-ab5a00a1b5e1)

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge, Safari

### Ready to Work?

- [X] I want to work on this issue

**Comment by oyepriyansh** [comment]
assigned to you.

**Comment by nishantshukla2884** [comment]
i can contribute ,can you please assign it to me @oyepriyansh

**Comment by oyepriyansh** [comment]
@CodeStrate can you share the progress?

**Comment by CodeStrate** [comment]
@oyepriyansh I had reconned around the codebase and noticed that you're using localstorage to fetch the theme.

its unsurprisingly only works for the icon, not the entire theme.

Two possible ways : remove the localStorage code since we're defaulting to dark theme. always.
or look where the localStorage fails for the entire website.
