### ISSUE TITLE
feat: Adding scroll to top button

### ISSUE THREAD

**Issue by Kritika30032002** [oyepriyansh/DevTweet#81]
### Description

Adding scroll to top button

### Ready to Work?

- [ ] I want to work on this issue

**Comment by IvySaskia** [comment]
I would like to make this issue

**Comment by oyepriyansh** [comment]
@IvySaskia assigned to you

**Comment by bangadam** [comment]
Hi @oyepriyansh i want to contribute to this task, please assign to me
