### ISSUE TITLE
feat:Adding animations using framer motion

### ISSUE THREAD

**Issue by M-A-N-I-K** [oyepriyansh/DevTweet#82]
### Description

I propose implementing subtle and elegant card reveal animations that trigger when the user scrolls down the page. These animations will not only make the content more visually appealing but also enhance the overall user engagement with our website.

### Ready to Work?

- [X] I want to work on this issue

**Comment by oyepriyansh** [comment]
assigned to you

**Comment by oyepriyansh** [comment]
@M-A-N-I-K  any updates?
