### ISSUE TITLE
feat: Create new post button not present, when going through posts

### ISSUE THREAD

**Issue by malay5** [oyepriyansh/DevTweet#84]
### Description

The button to add/create new posts is missing, when viewing the posts

### Screenshots

![2023-10-03 04_54_57-DevTweet - Unleash Your Developer Voice](https://github.com/oyepriyansh/DevTweet/assets/64472685/36584713-02e4-4455-850c-7f31ea9d1dc2)

### Ready to Work?

- [X] I want to work on this issue

**Comment by oyepriyansh** [comment]
assigned to you

**Comment by malay5** [comment]
Can you please add hacktoberfest tag?
