### ISSUE TITLE
feat: create a homepage 

### ISSUE THREAD

**Issue by piyushkdas0611** [oyepriyansh/DevTweet#85]
### Description

The Home and Posts Navigation basically gives you the same thing. If two different nav options are created it should have different functionality. Now I suggest two suggestions: either create a landing page as the home page, or in the post page add option to create a post.

### Ready to Work?

- [ ] I want to work on this issue

**Comment by oyepriyansh** [comment]
Maybe this issue should go in the feature requests section, not as a bug. It's a good idea; let me know if anyone wants to work on this issue.

**Comment by Vaibhav91one** [comment]
Can I work on this feature.

**Comment by oyepriyansh** [comment]
assigned to you.

**Comment by Vaibhav91one** [comment]
![image](https://github.com/oyepriyansh/DevTweet/assets/108279746/a73f89a7-ff2c-4628-b917-235a53ee86d7)
![image](https://github.com/oyepriyansh/DevTweet/assets/108279746/3bce0097-0781-41d3-8dc6-2d6d3f96c638)
@oyepriyansh is this good enough.

**Comment by oyepriyansh** [comment]
> ![image](https://github.com/oyepriyansh/DevTweet/assets/108279746/a73f89a7-ff2c-4628-b917-235a53ee86d7)
> ![image](https://github.com/oyepriyansh/DevTweet/assets/108279746/3bce0097-0781-41d3-8dc6-2d6d3f96c638)
> @oyepriyansh is this good enough.

Yep.

**Comment by Vaibhav91one** [comment]
@oyepriyansh that was really fast

**Comment by oyepriyansh** [comment]
> @oyepriyansh that was really fast

I am on Mobile rn, so got notification via app

**Comment by Vaibhav91one** [comment]
@oyepriyansh Is there any guide to how to make a PR for this repo?

**Comment by oyepriyansh** [comment]
> @oyepriyansh Is there any guide to how to make a PR for this repo?

Just make your changes and create a Pull Request as default

**Comment by Vaibhav91one** [comment]
> > @oyepriyansh Is there any guide to how to make a PR for this repo?
> 
> Just make your changes and create a Pull Request as default

okay

**Comment by Vaibhav91one** [comment]
> > > @oyepriyansh Is there any guide to how to make a PR for this repo?
> > 
> > 
> > Just make your changes and create a Pull Request as default
> 
> okay

Should i make a different branch for the feature or main only

**Comment by oyepriyansh** [comment]
> > > > @oyepriyansh Is there any guide to how to make a PR for this repo?
> > > 
> > > 
> > > Just make your changes and create a Pull Request as default
> > 
> > 
> > okay
> 
> Should i make a different branch for the feature or main only

You can create a Pull Request from any branch of your forked repository
