### ISSUE TITLE
Bug: Moon icon disappears after a reload and switches to sun icon in navbar

### ISSUE THREAD

**Issue by gaurab-khanal** [oyepriyansh/DevTweet#88]
### Description

When switching to dark mode moon icon appears which is fine but after a reload it is replaced by sun icon.

Current Behaviour after a reload: 
![image](https://github.com/oyepriyansh/DevTweet/assets/40165867/c0355589-277b-4fc9-83d8-439eb590d70b)
Expected Behaviour after a reload: 
![image](https://github.com/oyepriyansh/DevTweet/assets/40165867/4339932c-488b-4a07-9105-8d34a46df91f)

### What browsers are you seeing the problem on?

Chrome

### Ready to Work?

- [X] I want to work on this issue

**Comment by oyepriyansh** [comment]
assigned to you.

**Comment by gaurab-khanal** [comment]
@oyepriyansh can you look at the code and review it.
