### ISSUE TITLE
Enhancement: Header tags font size is not correct

### ISSUE THREAD

**Issue by yoursshahnawaz** [oyepriyansh/DevTweet#97]
### Screenshot:
![image](https://github.com/oyepriyansh/DevTweet/assets/54206065/fddc0f52-bcb0-4813-b3df-e7dd954d509a)

### This is how it would look with enhanced font sizes:
![image](https://github.com/oyepriyansh/DevTweet/assets/54206065/e9e6a9e5-7496-4e86-a9bb-0493236fb635)

**Please assign this issue to me. I already have a fix for it.**

**Comment by oyepriyansh** [comment]
assigned to you!

**Comment by yoursshahnawaz** [comment]
Fixed & merged
